name: Suggestion
description: >-
  Please use this template when you want to suggest a feature. Do not ask for mod updates or ports, they will come when they are ready.
title: '[Suggestion]: '
labels: ["enhancement"]
assignees:
  - Fuzss
body:
  - type: textarea
    id: suggestion
    attributes:
      label: Suggestion (Required)
      placeholder: >-
        ex. Here is my very awesome suggestion for your mod. It would be some much better if you could add that!
    validations:
      required: true
